version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_DATABASE: ev_charging_station
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    networks:
      - ev_network

  mysql_test:
    image: mysql:latest
    container_name: mysql_db_test
    restart: always
    ports:
      - "3308:3307"
    environment:
      MYSQL_TCP_PORT: 3307
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_DATABASE: test_ev_charging_station
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    networks:
      - ev_network

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_boot_app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - mysql_test

    networks:
      - ev_network

networks:
  ev_network:  # Custom network definition
    driver: bridge